### ISSUE TITLE
🤦‍♂️🤦‍♂️ you can see not styled version if you refresh too fast 🤦‍♂️🤦‍♂️

### ISSUE THREAD

**Issue by mariusgrigaitis** [RokasMuningis/arjaukraustomes.lt#5]
using chrome, hit refresh very fast. I usually refresh a lot.

you can see non-styled "ne" for a brief period of time

![image](https://user-images.githubusercontent.com/11269671/50651462-1691c200-0f8c-11e9-880a-222d3c962af3.png)

I think it was introduced with #3 

@RokasMuningis was it you?

This is a killer performance bottleneck which causes loss of sales ;/

**Comment by muningis** [comment]
can't reproduce. What kind of potato device are you using? It works fine on 2018 Macbook pro 15" i9....

**Comment by mariusgrigaitis** [comment]
Try turning on bitcoin miner

**Comment by T0mas3** [comment]
This is unusable. Please fix ASAP

**Comment by muningis** [comment]
@t0mas3 feel free to submit PR :)

**Comment by muningis** [comment]
can you reproduce it???

**Comment by mariusgrigaitis** [comment]
why closed????

**Comment by muningis** [comment]
@mariusgrigaitis - unreproducable, and no one runs bitcoin miners nowadays. Garliccoin is the thing

**Comment by mariusgrigaitis** [comment]
I will come to your desk and will reproduce on your super-fast PC

**Comment by muningis** [comment]
That sounds like threatening

**Comment by muningis** [comment]
Reopening this from hospital,  after I got attacked with party parrot
